### ISSUE TITLE
Problem on Mac OS Python 2.7

### ISSUE THREAD

**Issue by jbuchmann** [ericleepa/slackspeedtest#1]
MBP-15:slackspeedtest george$ python manager.py 
run speedtest_cli
Retrieving speedtest.net configuration...
Testing from Personal (181.91.42.61)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Telecom Argentina (Ramos Mejia) [27.34 km]: 32.878 ms
Testing download speed................................................................................
Download: 5.60 Mbit/s
Testing upload speed....................................................................................................
Upload: 1.50 Mbit/s

**Traceback (most recent call last):
  File "manager.py", line 59, in <module>
    do_speed_test()
  File "manager.py", line 17, in do_speed_test
    pingfloat = float(pingResult.replace('Ping: ', '').replace(' ms', ''))
ValueError: could not convert string to float: Retrieving speedtest.net configuration...**

Thanks in advance!

**Comment by ericleepa** [comment]
@jbuchmann I see what the issue is.  I originally ran speedtest_cli with the --simple flag.  I've updated the readme file to better explain this.  If you ad "--simple" in your config file for the variable
speedtest_cli_dir it should work.  Let me know if it doesn't.
